baseURL                   = "https://namile.me"
builddrafts                = false
languageCode               = "zn-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Namila Bandara"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  [[menu.main]]
    name                   = "Projects"
    weight                 = -100
    identifier             = "projects"
    url                    = "projects/"  
  [[menu.main]]
    name                   = "About"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/nb.png"               # from static/
  avatar                   = "img/profile.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Namila Bandara"
  description              = ["Tech Lover","Gamer","Sri Lankan"]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello Adventurer!"
  welcome_word             = "~ Welcome to My Personal Web ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "me@namila.me"
  github                   = "//github.com/namila007"
  linkedin                 = "//linkedin.com/in/namila007"
  facebook                 = "//facebook.com/namila007"
  twitter                  = "//twitter.com/namila" 
  instagram                = "//instagram.com/namila007"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics and disqus set by env